#!/bin/bash

while true; do
clear

echo -e "\e[36m"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 VPS HOSTING MANAGER"
echo "Made by Zojo"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
cat << "EOF"
████████╗██████╗ ██╗███████╗███████╗██████╗ 
╚══██╔══╝██╔══██╗██║╚══███╔╝██╔════╝██╔══██╗
   ██║   ██████╔╝██║  ███╔╝ █████╗  ██████╔╝
   ██║   ██╔══██╗██║ ███╔╝  ██╔══╝  ██╔══██╗
   ██║   ██║  ██║██║███████╗███████╗██║  ██║
   ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝╚══════╝╚═╝  ╚═╝
EOF

echo ""
echo "1) Install Cloudflare"
echo "2) Install HvmPanel"
echo "3) Exit"
echo ""
read -p "Select option [1-3]: " opt

case $opt in
  1)
    bash <(curl -s https://raw.githubusercontent.com/Trizer540/Cloudflare/refs/heads/main/cloudflare)
    ;;
  2)
    bash <(curl -s https://raw.githubusercontent.com/Trizer540/HvmPanel/refs/heads/main/panel)
    ;;
  3)
    exit 0
    ;;
  *)
    echo "❌ Invalid Option"
    sleep 1
    ;;
esac
done
