#!/bin/bash

while true; do
clear

echo -e "\e[36m"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 VPS HOSTING MANAGER"
echo "Made by Zojo"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
cat << "EOF"
████████╗██████╗ ██╗███████╗███████╗██████╗ 
╚══██╔══╝██╔══██╗██║╚══███╔╝██╔════╝██╔══██╗
   ██║   ██████╔╝██║  ███╔╝ █████╗  ██████╔╝
   ██║   ██╔══██╗██║ ███╔╝  ██╔══╝  ██╔══██╗
   ██║   ██║  ██║██║███████╗███████╗██║  ██║
   ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝╚══════╝╚═╝  ╚═╝
EOF

echo ""
echo "1) Install Cloudflare"
echo "2) Install HvmPanel"
echo "3) Exit"
echo ""
read -p "Select option [1-3]: " opt

case $opt in
  1)
    bash <(curl -s https://raw.githubusercontent.com/Trizer540/Cloudflare/refs/heads/main/cloudflare)
    ;;
  2)
    sudo apt update
    sudo apt install git -y
    git clone https://github.com/DreamHost2ws/Vpanel3.1.git
    sudo apt install python3-pip -y
    cd Vpanel3.1
    pip3 install flask flask-socketio flask_login docker paramiko python-dotenv psutil flask-limiter ecdsa
    python3 hvm.py
    ;;
  3)
    exit 0
    ;;
  *)
    echo "❌ Invalid Option"
    sleep 1
    ;;
esac
done
